
import { GoogleGenAI } from "@google/genai";

if (!process.env.API_KEY) {
    console.warn("API_KEY environment variable not set. Using a placeholder key. Please set your API key for the app to function.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "YOUR_API_KEY_HERE" });

export const generateArtFromFeelings = async (feelings: string): Promise<string> => {
    try {
        const fullPrompt = `Create a visually stunning, abstract therapeutic art piece that represents the following feeling or situation: "${feelings}". The style should be dreamlike and expressive, using a soft, calming color palette. Focus on textures and symbolic imagery rather than literal representation.`;

        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: fullPrompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with Gemini API:", error);
        throw new Error("Failed to create art. The connection to the creative muse seems to be lost. Please try again later.");
    }
};
